version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_ROOT_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=hotels
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    links:
      - db

volumes:
  pg-data:
